[INFO -- 2018-09-25 00:18:23]
Starting flip_value script
version: 1.1
[INFO -- 2018-09-25 00:18:23]
Initialization strings:
[INFO -- 2018-09-25 00:18:23]
(1) file /tmp/knapsack/ga
[INFO -- 2018-09-25 00:18:23]
initSignal:1
[INFO -- 2018-09-25 00:18:23]
endSignal:3.5
[INFO -- 2018-09-25 00:18:23]
faultModel:2
[EXCEPTION -- 2018-09-25 00:18:24]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[INFO -- 2018-09-25 00:18:25]
Backtrace BEGIN:
#0  __memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:525
#1  0x000055555555a0d0 in std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<int> (__first=0x555555786ef0, __last=0x555555787210, __result=0x55555578b390) at /usr/include/c++/7/bits/stl_algobase.h:368
#2  0x00005555555595f2 in std::__copy_move_a<false, int const*, int*> (__first=0x555555786ef0, __last=0x555555787210, __result=0x55555578b390) at /usr/include/c++/7/bits/stl_algobase.h:386
#3  0x000055555555a8a1 in std::__copy_move_a2<false, __gnu_cxx::__normal_iterator<int const*, std::vector<int, std::allocator<int> > >, int*> (__first=0, __last=816, __result=0x55555578b390) at /usr/include/c++/7/bits/stl_algobase.h:424
#4  0x0000555555559fd6 in std::copy<__gnu_cxx::__normal_iterator<int const*, std::vector<int, std::allocator<int> > >, int*> (__first=0, __last=816, __result=0x55555578b390) at /usr/include/c++/7/bits/stl_algobase.h:456
#5  0x000055555555948e in std::__uninitialized_copy<true>::__uninit_copy<__gnu_cxx::__normal_iterator<int const*, std::vector<int, std::allocator<int> > >, int*> (__first=0, __last=816, __result=0x55555578b390) at /usr/include/c++/7/bits/stl_uninitialized.h:101
#6  0x00005555555583be in std::uninitialized_copy<__gnu_cxx::__normal_iterator<int const*, std::vector<int, std::allocator<int> > >, int*> (__first=0, __last=816, __result=0x55555578b390) at /usr/include/c++/7/bits/stl_uninitialized.h:134
#7  0x0000555555556f6d in std::__uninitialized_copy_a<__gnu_cxx::__normal_iterator<int const*, std::vector<int, std::allocator<int> > >, int*, int> (__first=0, __last=816, __result=0x55555578b390) at /usr/include/c++/7/bits/stl_uninitialized.h:289
#8  0x0000555555555ed1 in std::vector<int, std::allocator<int> >::vector (this=0x55555578a030, __x=std::vector of length 200, capacity 200 = {...}) at /usr/include/c++/7/bits/stl_vector.h:331
#9  0x0000555555557e39 in chromossome::chromossome (this=0x55555578a030) at knapsackga.cpp:42
#10 0x0000555555557e96 in __gnu_cxx::new_allocator<chromossome>::construct<chromossome, chromossome const&> (this=0x7fffffffd8f0, __p=0x55555578a030, __args#0=...) at /usr/include/c++/7/ext/new_allocator.h:136
#11 0x0000555555556a90 in std::allocator_traits<std::allocator<chromossome> >::construct<chromossome, chromossome const&> (__a=..., __p=0x55555578a030, __args#0=...) at /usr/include/c++/7/bits/alloc_traits.h:475
#12 0x0000555555555cf0 in std::vector<chromossome, std::allocator<chromossome> >::push_back (this=0x7fffffffd8f0, __x=...) at /usr/include/c++/7/bits/stl_vector.h:943
#13 0x00005555555554fd in genetic_algorithm () at knapsackga.cpp:107
#14 0x00005555555558d7 in main () at knapsackga.cpp:137

520	in ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S

Backtrace END
Fliping a bit of the value pointed by a pointer
Fliping value of field: std::_Vector_base<chromossome, std::allocator<chromossome> >
Fliping value of field: _M_impl
Fliping value of field: _M_start
Fliping a bit of the pointer
Memory content before bitflip:0x900x9b0x780x550x550x550x000x00
Fault Model: Random bit-flip
base address to flip value: 0x7fffffffd8f0
address max offset: 8
Memory content after  bitflip:0x900x610x0e0x390xc90xc40xcd0x14
frame name: std::vector<chromossome, std::allocator<chromossome> >::push_back
symbol name: this
symbol filename: knapsackga.cpp
symbol line: 0
value: 0x7fffffffd8f0
value address: 0x7fffffffd898
Type: The type is a pointer.
Type sizeof: 8

[INFO -- 2018-09-25 00:18:25]
Fault Injection Successful after 2.0346009731292725s
[INFO -- 2018-09-25 00:18:25]
event type: exit
[EXCEPTION -- 2018-09-25 00:18:25]
exit code: no exit code available
