[INFO -- 2018-12-01 02:55:25]
Starting flip_value script
version: 1.1
[INFO -- 2018-12-01 02:55:25]
Initialization strings:
[INFO -- 2018-12-01 02:55:25]
(1) file /tmp/knapsack/ga
[INFO -- 2018-12-01 02:55:25]
initSignal:0
[INFO -- 2018-12-01 02:55:25]
endSignal:13
[INFO -- 2018-12-01 02:55:25]
faultModel:3
[EXCEPTION -- 2018-12-01 02:55:31]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[EXCEPTION -- 2018-12-01 02:55:31]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-12-01 02:55:31]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7490f5d in __GI_abort () at abort.c:90
#2  0x00007ffff74d928d in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7600528 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff74e064a in malloc_printerr (action=<optimized out>, str=0x7ffff76008b0 "double free or corruption (out)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5426
#4  0x00007ffff74e273e in _int_free (av=0x7ffff7832c20 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4175
#5  0x00007ffff74e744e in __GI___libc_free (mem=<optimized out>) at malloc.c:3145
#6  0x00005555555597ea in __gnu_cxx::new_allocator<int>::deallocate (this=0x7fffffffd800, __p=0x555555784100) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x00005555555587a6 in std::allocator_traits<std::allocator<int> >::deallocate (__a=..., __p=0x555555784100, __n=244) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x0000555555557316 in std::_Vector_base<int, std::allocator<int> >::_M_deallocate (this=0x7fffffffd800, __p=0x555555784100, __n=244) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x0000555555556b53 in std::_Vector_base<int, std::allocator<int> >::~_Vector_base (this=0x7fffffffd800, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:162
#10 0x0000555555555e7d in std::vector<int, std::allocator<int> >::~vector (this=0x7fffffffd800, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#11 0x0000555555555329 in crossover (pai=std::vector of length 200, capacity 200 = {...}, mae=std::vector of length 200, capacity 200 = {...}, filho1=std::vector of length 200, capacity 200 = {...}, filho2=std::vector of length 200, capacity 200 = {...}) at knapsackga.cpp:72
#12 0x00005555555555c7 in genetic_algorithm () at knapsackga.cpp:104
#13 0x0000555555555a9b in main () at knapsackga.cpp:141

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Fliping value of field: __val
Fliping array at pos: 9
Memory content before bitflip:0x650xc60xdd0xf70xff0x7f0x000x00
Fault Model: Zero bit-flip
base address to flip value: 0x7fffffffd158
address max offset: 8
Memory content after  bitflip:0x000x000x000x000x000x000x000x00
frame name: __GI_raise
symbol name: set
symbol filename: ../sysdeps/unix/sysv/linux/raise.c
symbol line: 39
value: {__val = {0, 0, 0, 140737353902576, 140737488344208, 140737488343440, 140737488344440, 2049, 2, 0, 0, 1925120, 1924580, 1924580, 0, 5}}
value address: 0x7fffffffd110
Type: The type is a structure.
Type sizeof: 128
Field name: __val
Field Type: The type is an array.
Field Type sizeof: 128

[INFO -- 2018-12-01 02:55:31]
Fault Injection Successful after 6.584984302520752s
[INFO -- 2018-12-01 02:55:31]
event type: exit
[EXCEPTION -- 2018-12-01 02:55:31]
exit code: no exit code available
