[INFO -- 2018-09-21 20:48:14]
Starting flip_value script
version: 1.1
[INFO -- 2018-09-21 20:48:14]
Initialization strings:
[INFO -- 2018-09-21 20:48:14]
(1) file /tmp/knapsack/dp
[INFO -- 2018-09-21 20:48:14]
initSignal:1
[INFO -- 2018-09-21 20:48:14]
endSignal:3
[INFO -- 2018-09-21 20:48:14]
faultModel:2
[EXCEPTION -- 2018-09-21 20:48:16]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-09-21 20:48:16]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[EXCEPTION -- 2018-09-21 20:48:16]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-09-21 20:48:16]
Backtrace BEGIN:
#0  std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::operator[] (this=0x7fffffffda30, __n=66) at /usr/include/c++/7/bits/stl_vector.h:795
#1  0x0000555555554fdf in knapSack (W=588593, n=200, val=std::vector of length 230, capacity 286 = {...}, wt=std::vector of length 210, capacity 266 = {...}) at knapsackdp.cpp:23
#2  0x0000555555555375 in main () at knapsackdp.cpp:54

790	       *  Note that data access with this operator is unchecked and
791	       *  out_of_range lookups are not defined. (For checked lookups
792	       *  see at().)
793	       */
794	      reference
795	      operator[](size_type __n) _GLIBCXX_NOEXCEPT
796	      {
797		__glibcxx_requires_subscript(__n);
798		return *(this->_M_impl._M_start + __n);
799	      }

Backtrace END
Memory content before bitflip:0x420x000x000x000x000x000x000x00
Fault Model: Random bit-flip
base address to flip value: 0x7fffffffd930
address max offset: 8
Memory content after  bitflip:0x9b0x0e0x1a0xd50x820x170x2b0xae
frame name: std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::operator[]
symbol name: __n
symbol filename: /usr/include/c++/7/bits/stl_vector.h
symbol line: 795
value: 12550150637286461083
value address: 0x7fffffffd930
Type: The type is an integer type.
Type sizeof: 8

[INFO -- 2018-09-21 20:48:16]
Fault Injection Successful after 2.518981695175171s
[INFO -- 2018-09-21 20:48:18]
event type: exit
[EXCEPTION -- 2018-09-21 20:48:18]
exit code: no exit code available
