[INFO -- 2018-10-19 06:06:26]
Starting flip_value script
version: 1.1
[INFO -- 2018-10-19 06:06:26]
Initialization strings:
[INFO -- 2018-10-19 06:06:26]
(1) file /tmp/knapsack/mf
[INFO -- 2018-10-19 06:06:26]
initSignal:1
[INFO -- 2018-10-19 06:06:26]
endSignal:3
[INFO -- 2018-10-19 06:06:26]
faultModel:3
[EXCEPTION -- 2018-10-19 06:06:28]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-10-19 06:06:29]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-10-19 06:06:29]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-10-19 06:06:29]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-10-19 06:06:31]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff747e801 in __GI_abort () at abort.c:79
#2  0x00007ffff74c7897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff75f4b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff74ce90a in malloc_printerr (str=str@entry=0x7ffff75f2d88 "free(): invalid pointer") at malloc.c:5350
#4  0x00007ffff74d5e1c in _int_free (have_lock=0, p=0x555555770ef0, av=0x7ffff7829c40 <main_arena>) at malloc.c:4157
#5  __GI___libc_free (mem=0x555555770f00) at malloc.c:3124
#6  0x0000555555556cf8 in __gnu_cxx::new_allocator<int>::deallocate (this=0x555555759170 <weights>, __p=0x555555770f00) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x0000555555556893 in std::allocator_traits<std::allocator<int> >::deallocate (__a=..., __p=0x555555770f00, __n=304) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x000055555555615c in std::_Vector_base<int, std::allocator<int> >::_M_deallocate (this=0x555555759170 <weights>, __p=0x555555770f00, __n=304) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x00005555555559c3 in std::_Vector_base<int, std::allocator<int> >::~_Vector_base (this=0x555555759170 <weights>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:162
#10 0x000055555555580b in std::vector<int, std::allocator<int> >::~vector (this=0x555555759170 <weights>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#11 0x00007ffff7481041 in __run_exit_handlers (status=0, listp=0x7ffff7829718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#12 0x00007ffff748113a in __GI_exit (status=<optimized out>) at exit.c:139
#13 0x00007ffff745fb9e in __libc_start_main (main=0x55555555529b <main()>, argc=1, argv=0x7fffffffdf58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf48) at ../csu/libc-start.c:344
#14 0x0000555555554dfa in _start ()

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Memory content before bitflip:0x00
Fault Model: Zero bit-flip
base address to flip value: 0x7ffff782ad6c 
address max offset: 1
Memory content after  bitflip:0x00
frame name: __run_exit_handlers
symbol name: __exit_funcs_done
symbol filename: exit.c
symbol line: 31
value: false
value address: 0x7ffff782ad6c <__exit_funcs_done>
Type: A boolean type.
Type sizeof: 1

[INFO -- 2018-10-19 06:06:31]
Fault Injection Successful after 5.79864501953125s
[INFO -- 2018-10-19 06:06:31]
event type: exit
[EXCEPTION -- 2018-10-19 06:06:31]
exit code: no exit code available
