[INFO -- 2018-09-25 09:10:29]
Starting flip_value script
version: 1.1
[INFO -- 2018-09-25 09:10:29]
Initialization strings:
[INFO -- 2018-09-25 09:10:29]
(1) file /tmp/knapsack/ga
[INFO -- 2018-09-25 09:10:29]
initSignal:1
[INFO -- 2018-09-25 09:10:29]
endSignal:3.5
[INFO -- 2018-09-25 09:10:29]
faultModel:3
[EXCEPTION -- 2018-09-25 09:10:31]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-09-25 09:10:31]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-09-25 09:10:31]
gdbException: Cannot access memory at address 0x0
[INFO -- 2018-09-25 09:10:31]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7490f5d in __GI_abort () at abort.c:90
#2  0x00007ffff74d928d in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7600528 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff74e064a in malloc_printerr (action=<optimized out>, str=0x7ffff76008b0 "double free or corruption (out)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5426
#4  0x00007ffff74e273e in _int_free (av=0x7ffff7832c20 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4175
#5  0x00007ffff74e744e in __GI___libc_free (mem=<optimized out>) at malloc.c:3145
#6  0x000055555555955c in __gnu_cxx::new_allocator<int>::deallocate (this=0x555555776460, __p=0x555555786140) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x0000555555558518 in std::allocator_traits<std::allocator<int> >::deallocate (__a=..., __p=0x555555786140, __n=18446744073709551008) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x0000555555557086 in std::_Vector_base<int, std::allocator<int> >::_M_deallocate (this=0x555555776460, __p=0x555555786140, __n=18446744073709551008) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x000055555555689d in std::_Vector_base<int, std::allocator<int> >::~_Vector_base (this=0x555555776460, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:162
#10 0x0000555555555bed in std::vector<int, std::allocator<int> >::~vector (this=0x555555776460, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#11 0x0000555555555b62 in chromossome::~chromossome (this=0x555555776460, __in_chrg=<optimized out>) at knapsackga.cpp:42
#12 0x00005555555599b7 in std::_Destroy<chromossome> (__pointer=0x555555776460) at /usr/include/c++/7/bits/stl_construct.h:98
#13 0x0000555555558f21 in std::_Destroy_aux<false>::__destroy<chromossome*> (__first=0x555555776460, __last=0x555555776540) at /usr/include/c++/7/bits/stl_construct.h:108
#14 0x0000555555557e12 in std::_Destroy<chromossome*> (__first=0x555555776400, __last=0x555555776540) at /usr/include/c++/7/bits/stl_construct.h:137
#15 0x0000555555556a49 in std::_Destroy<chromossome*, chromossome> (__first=0x555555776400, __last=0x555555776540) at /usr/include/c++/7/bits/stl_construct.h:206
#16 0x0000555555555c81 in std::vector<chromossome, std::allocator<chromossome> >::~vector (this=0x7fffffffd870, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:434
#17 0x0000555555555088 in tournament (pop=std::vector of length 40, capacity 64 = {...}) at knapsackga.cpp:59
#18 0x0000555555555447 in genetic_algorithm () at knapsackga.cpp:103
#19 0x00005555555558d7 in main () at knapsackga.cpp:137

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Fliping value of field: __val
Fliping array at pos: 14
Memory content before bitflip:0x000x000x000x000x000x000x000x00
Fault Model: Zero bit-flip
base address to flip value: 0x7fffffffd130
address max offset: 8
Memory content after  bitflip:0x000x000x000x000x000x000x000x00
frame name: __GI_raise
symbol name: set
symbol filename: ../sysdeps/unix/sysv/linux/raise.c
symbol line: 39
value: {__val = {0, 0, 0, 140737353903824, 140737488343984, 140737488343360, 140737488344216, 2049, 2, 140737351893968, 0, 1396736, 1393508, 1393508, 0, 5}}
value address: 0x7fffffffd0c0
Type: The type is a structure.
Type sizeof: 128
Field name: __val
Field Type: The type is an array.
Field Type sizeof: 128

[INFO -- 2018-09-25 09:10:31]
Fault Injection Successful after 2.8831746578216553s
[INFO -- 2018-09-25 09:10:31]
event type: exit
[EXCEPTION -- 2018-09-25 09:10:31]
exit code: no exit code available
