[INFO -- 2018-12-08 22:03:40]
Starting flip_value script
version: 1.1
[INFO -- 2018-12-08 22:03:40]
Initialization strings:
[INFO -- 2018-12-08 22:03:40]
(1) file /tmp/knapsack/sa
[INFO -- 2018-12-08 22:03:40]
initSignal:0
[INFO -- 2018-12-08 22:03:40]
endSignal:9
[INFO -- 2018-12-08 22:03:40]
faultModel:2
[EXCEPTION -- 2018-12-08 22:03:43]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-12-08 22:03:43]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-12-08 22:03:44]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6ede801 in __GI_abort () at abort.c:79
#2  0x00007ffff6f27897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7054b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6f2e90a in malloc_printerr (str=str@entry=0x7ffff70567a8 "munmap_chunk(): invalid pointer") at malloc.c:5350
#4  0x00007ffff6f35ecc in munmap_chunk (p=0x5555557718b1) at malloc.c:2846
#5  __GI___libc_free (mem=0x5555557718c1) at malloc.c:3117
#6  0x0000555555556d66 in __gnu_cxx::new_allocator<int>::deallocate (this=0x555555759060 <val2>, __p=0x5555557718c1) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x0000555555556912 in std::allocator_traits<std::allocator<int> >::deallocate (__a=..., __p=0x5555557718c1, __n=231) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x0000555555556176 in std::_Vector_base<int, std::allocator<int> >::_M_deallocate (this=0x555555759060 <val2>, __p=0x5555557718c1, __n=231) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x0000555555555eb1 in std::_Vector_base<int, std::allocator<int> >::~_Vector_base (this=0x555555759060 <val2>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:162
#10 0x0000555555555949 in std::vector<int, std::allocator<int> >::~vector (this=0x555555759060 <val2>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#11 0x00007ffff6ee1041 in __run_exit_handlers (status=0, listp=0x7ffff7289718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#12 0x00007ffff6ee113a in __GI_exit (status=<optimized out>) at exit.c:139
#13 0x000055555555504b in exit_gracefully () at knapsacksa.cpp:40
#14 0x0000555555555200 in cost (solution=std::vector of length 200, capacity 200 = {...}) at knapsacksa.cpp:66
#15 0x000055555555534c in simulated_annealing () at knapsacksa.cpp:92
#16 0x0000555555555658 in main () at knapsacksa.cpp:146

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Fliping a bit of the value pointed by a reference
Fliping value of field: std::_Vector_base<int, std::allocator<int> >
Fliping value of field: _M_impl
Fliping value of field: _M_finish
Fliping a bit of the pointer
Memory content before bitflip:0xe00x2a0x770x550x550x550x000x00
Fault Model: Random bit-flip
base address to flip value: 0x7fffffffd748
address max offset: 8
Memory content after  bitflip:0xb00x420x030x140x040xc60x150x25
frame name: cost
symbol name: solution
symbol filename: knapsacksa.cpp
symbol line: 51
value: std::vector of length 668041462434432700, capacity 200 = {1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1...}
value address: 0x7fffffffd740
Type: A reference type.
Type sizeof: 8

[INFO -- 2018-12-08 22:03:44]
Fault Injection Successful after 4.238143444061279s
[INFO -- 2018-12-08 22:03:44]
event type: exit
[EXCEPTION -- 2018-12-08 22:03:44]
exit code: no exit code available
